# ${projectName}

A NestJS application generated by **Scaffy**.

## Tech Stack

- **Framework:** NestJS
- **ORM:** TypeORM
- **Database:** PostgreSQL
- **Language:** TypeScript
- **Validation:** class-validator / class-transformer
<#if openApiSupport>
- **API Docs:** Swagger (OpenAPI)
</#if>

## Getting Started

### Prerequisites

- Node.js >= 18
- PostgreSQL

### Installation

```bash
npm install
```

### Configuration

Copy the environment file and update values:

```bash
cp .env.example .env
```

### Running the app

```bash
# development
npm run start:dev

# production
npm run start:prod
```

### Testing

```bash
npm run test
```

<#if openApiSupport>
### API Documentation

Once the app is running, visit: [http://localhost:3000/api](http://localhost:3000/api)
</#if>

## Entities

<#list preparedEntities as entity>
- **${entity.name}**
</#list>
