# ${projectName}

A Django REST Framework application generated by **Scaffy**.

## Tech Stack

- **Framework:** Django + Django REST Framework
- **ORM:** Django ORM
- **Database:** PostgreSQL
- **Language:** Python 3.11+
<#if openApiSupport>
- **API Docs:** drf-spectacular (OpenAPI 3)
</#if>

## Getting Started

### Prerequisites

- Python 3.11+
- PostgreSQL

### Installation

```bash
python -m venv venv
source venv/bin/activate  # On Windows: venv\Scripts\activate
pip install -r requirements.txt
```

### Configuration

Copy the environment file and update values:

```bash
cp .env.example .env
```

### Database Setup

```bash
python manage.py makemigrations
python manage.py migrate
python manage.py createsuperuser
```

### Running the Server

```bash
python manage.py runserver
```

<#if openApiSupport>
### API Documentation

Once the server is running, visit:
- Swagger UI: [http://localhost:8000/api/schema/swagger-ui/](http://localhost:8000/api/schema/swagger-ui/)
- ReDoc: [http://localhost:8000/api/schema/redoc/](http://localhost:8000/api/schema/redoc/)
</#if>

### Running Tests

```bash
python manage.py test
```

## Entities

<#list preparedEntities as entity>
- **${entity.name}**
</#list>
